update phpunit.yml

diff --git a/.github/workflows/phpunit.yml b/.github/workflows/phpunit.yml
--- a/.github/workflows/phpunit.yml
+++ b/.github/workflows/phpunit.yml
@@ -57,11 +57,11 @@ jobs:
           done
       - name: Crear base de datos
         run: |
-          mysql -h mysql -u root -ptu -e "CREATE DATABASE IF NOT EXISTS emergencia_db;"
+          mysql -h 127.0.0.1  -u root -ptu -e "CREATE DATABASE IF NOT EXISTS emergencia_db;"
 
       - name: Importar base de datos desde db_emergencias.sql
         run: |
-          mysql -h mysql -u testuser -ptestpassword emergencia_db < db_emergencias.sql || echo "Error al importar db_emergencias.sql"
+          mysql -h 127.0.0.1 -u testuser -ptestpassword emergencia_db < db_emergencias.sql || echo "Error al importar db_emergencias.sql"
 
 
 
